### PR TITLE
Spline seed.

### PR DESCRIPTION
**Pull request by jimgreen**

### CODE REVIEW

**Comment by jimgreen** [comment]
Like Kris predicted earlier, the testing failed due to import errors: 1) Scipy is non-existing, or 2) Scipy's dependence on libgfortran is not properly handled.

Maybe we can return a empty list and give a warning?

**Comment by KristoforMaynard** [comment]
TODO: rebase onto latest dev... this should fix CI. Also, maybe squash it all into a single commit?

**Comment by jimgreen** [comment]
Done except for the plot generation part.

**Comment by KristoforMaynard** [comment]
Incorporated into release 0.99.0

**Pull request closed without merging**
